# syntax=docker/dockerfile:1

# v0.11.2
FROM ghcr.io/astral-sh/uv:0.11.2@sha256:a4b988852921cbd194dcb3dfe7e355a19ecfd77563fb821ad9d2cd6582212055 AS uv

# debian
FROM mcr.microsoft.com/devcontainers/base:debian@sha256:cee2043f4bd75a18652f016ee4478f98e454406daf246d798d68775bf2349d14

COPY --from=uv /uv /uvx /usr/local/bin/

# just 1.48.1, pre-commit 4.5.1, bun 1.3.11
RUN UV_TOOL_BIN_DIR=/usr/local/bin uv tool install just==1.48.1 \
  && UV_TOOL_BIN_DIR=/usr/local/bin uv tool install pre-commit==4.5.1 \
  && curl -fsSL https://bun.sh/install | bash -s -- bun-v1.3.11 \
  && mv /root/.bun/bin/bun /usr/local/bin/ \
  && mv /root/.bun/bin/bunx /usr/local/bin/ \
  && rm -rf /root/.bun
