# syntax=docker/dockerfile:1

# uv v0.11.2
FROM ghcr.io/astral-sh/uv:0.11.2@sha256:c4f5de312ee66d46810635ffc5df34a1973ba753e7241ce3a08ef979ddd7bea5 AS uv

# bun v1.3.11
FROM oven/bun:1.3.11@sha256:0733e50325078969732ebe3b15ce4c4be5082f18c4ac1a0f0ca4839c2e4e42a7 AS bun

# debian
FROM mcr.microsoft.com/devcontainers/base:debian@sha256:cee2043f4bd75a18652f016ee4478f98e454406daf246d798d68775bf2349d14

COPY --from=uv /uv /uvx /usr/local/bin/
COPY --from=bun /usr/local/bin/bun /usr/local/bin/bunx /usr/local/bin/

# just 1.48.1, pre-commit 4.5.1
RUN UV_TOOL_BIN_DIR=/usr/local/bin UV_TOOL_DIR=/opt/uv-tools uv tool install just==1.48.1 \
  && UV_TOOL_BIN_DIR=/usr/local/bin UV_TOOL_DIR=/opt/uv-tools uv tool install pre-commit==4.5.1
