#!/usr/bin/env -S uv run --script
# SPDX-FileCopyrightText: 2026 Avish Jha <avish.j@pm.me>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# /// script
# requires-python = ">=3.13"
# dependencies = []
# ///
"""Make a meaningful change in the smoke-repo PR branch.

Run from cwd of smoke-repo PR branch; produces edits that trigger every
path-filtered workflow in the generated ci.yml. Path-filter coverage:

- source -> src/pages/index.astro (trailing HTML comment)
- tests  -> tests/verify.test.ts (new vitest noop)
- docs   -> README.md (trailing HTML marker)

Filters intentionally NOT triggered:
- configs    -> astro.config.mjs, package.json, bun.lock, tsconfig.json
- workflows  -> we don't mutate CI itself
"""

from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path

STAMP = dt.datetime.now(dt.UTC).isoformat()
MARK = f"verify {STAMP}"


def append_line(path: Path, line: str) -> None:
    with path.open("a", encoding="utf-8") as f:
        f.write(line if line.endswith("\n") else line + "\n")


def add_noop_test() -> None:
    Path("tests/verify.test.ts").write_text(
        "// SPDX-FileCopyrightText: 2026 Avish Jha <avish.j@pm.me>\n"
        "//\n"
        "// SPDX-License-Identifier: AGPL-3.0-or-later\n"
        "\n"
        f"// Auto-generated by verify/trigger.py at {STAMP}.\n\n"
        'import { describe, expect, it } from "vitest";\n\n'
        'describe("verify", () => {\n'
        '  it("noop", () => {\n'
        "    expect(true).toBe(true);\n"
        "  });\n"
        "});\n",
        encoding="utf-8",
    )


def main() -> int:
    append_line(Path("src/pages/index.astro"), f"<!-- {MARK} -->")
    add_noop_test()
    append_line(Path("README.md"), f"\n<!-- {MARK} -->")
    return 0


if __name__ == "__main__":
    sys.exit(main())
