# SPDX-FileCopyrightText: 2026 Avish J <avish.j@pm.me>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: OSV-Scanner

on:
  workflow_call:
    inputs:
      scan-mode:
        description: "Scan mode: 'ci' for PR differential scanning, 'weekly' for full repository scan"
        required: true
        type: string
      scan-args:
        description: "Custom osv-scanner arguments (See https://google.github.io/osv-scanner/usage/ for options, you cannot set --format or --output)"
        type: string
        default: |-
          -r
          ./
      results-file-name:
        description: "File name of the result SARIF file"
        type: string
        default: results.sarif
      download-artifact:
        description: "Optional artifact to download for scanning"
        required: false
        default: ""
        type: string
      upload-sarif:
        description: "Whether to upload to Security > Code Scanning"
        type: boolean
        required: false
        default: true
      fail-on-vuln:
        description: "Whether to fail the action on vulnerability found"
        type: boolean
        default: true
      matrix-property:
        description: "Optional string for matrix strategies (E.g. 'amd64-')"
        type: string
        default: ""
      checkout-submodules:
        description: "Whether to check out submodules or not. Passed on to `submodules` argument of `actions/checkout`"
        type: boolean
        default: false
      ref:
        description: "Whether to checkout a custom branch/tag/commit for scanning other than the default branch"
        type: string
        default: ""

permissions: {}

jobs:
  scan-ci:
    if: inputs.scan-mode == 'ci'
    name: OSV CI Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          submodules: ${{ inputs.checkout-submodules }}
          # Do persist credentials, as we need it for the git checkout later
      - name: "Checkout target branch"
        run: |
          git checkout $GITHUB_BASE_REF
          git submodule update --recursive
      - name: "Run scanner on existing code"
        uses: google/osv-scanner-action/osv-scanner-action@8018483926dd235b3013d8c88023e644b9f8e09e # v2.3.3
        continue-on-error: true
        with:
          scan-args: |-
            --format=json
            --output=${{ inputs.matrix-property }}old-results.json
            ${{ inputs.scan-args }}
      - name: "Checkout current branch"
        # Use -f in case any changes were made by osv-scanner (there should be no changes)
        run: |
          git checkout -f $GITHUB_SHA
          git submodule update --recursive
      - name: "Run scanner on new code"
        uses: google/osv-scanner-action/osv-scanner-action@8018483926dd235b3013d8c88023e644b9f8e09e # v2.3.3
        with:
          scan-args: |-
            --format=json
            --output=${{ inputs.matrix-property }}new-results.json
            ${{ inputs.scan-args }}
        continue-on-error: true
      - name: "Run osv-scanner-reporter"
        uses: google/osv-scanner-action/osv-reporter-action@8018483926dd235b3013d8c88023e644b9f8e09e # v2.3.3
        with:
          scan-args: |-
            --output=${{ inputs.matrix-property }}${{ inputs.results-file-name }}
            --old=${{ inputs.matrix-property }}old-results.json
            --new=${{ inputs.matrix-property }}new-results.json
            --gh-annotations=true
            --fail-on-vuln=${{ inputs.fail-on-vuln }}
      - name: "Upload artifact"
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: OSV Scanner SARIF file
          path: ${{ inputs.matrix-property }}${{ inputs.results-file-name }}
          retention-days: 5
      - name: "Upload old scan json results"
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ inputs.matrix-property }}old-json-results
          path: ${{ inputs.matrix-property }}old-results.json
          retention-days: 5
      - name: "Upload new scan json results"
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ inputs.matrix-property }}new-json-results
          path: ${{ inputs.matrix-property }}new-results.json
          retention-days: 5
      - name: "Upload to code-scanning"
        id: "upload_artifact"
        if: ${{ !cancelled() && inputs.upload-sarif == true }}
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
        with:
          sarif_file: ${{ inputs.matrix-property }}${{ inputs.results-file-name }}
      - name: "Print Code Scanning PR URL"
        if: "${{ !cancelled() && inputs.upload-sarif == true }}"
        run: |
          echo "View the OSV-Scanner results for this PR in the 'Security' tab, using the following link:"
          echo "${{ github.server_url }}/${{ github.repository }}/security/code-scanning?query=pr%3A${{ github.event.pull_request.number }}"
      - name: "Error troubleshooter"
        if: ${{ always() && steps.upload_artifact.outcome == 'failure' }}
        run: |
          echo "::error::Artifact upload failed. This is most likely caused by a error during scanning earlier in the workflow."

  scan-weekly:
    if: inputs.scan-mode == 'weekly'
    name: OSV Weekly Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          submodules: ${{ inputs.checkout-submodules }}
          ref: ${{ inputs.ref }}
      - name: "Download custom artifact if specified"
        uses: actions/download-artifact@v7
        if: "${{ inputs.download-artifact != '' }}"
        with:
          name: "${{ inputs.download-artifact }}"
          path: "./"
      - name: "Run scanner"
        uses: google/osv-scanner-action/osv-scanner-action@8018483926dd235b3013d8c88023e644b9f8e09e # v2.3.3
        with:
          scan-args: |-
            --output=${{ inputs.matrix-property }}results.json
            --format=json
            ${{ inputs.scan-args }}
        continue-on-error: true
      - name: "Run osv-scanner-reporter"
        uses: google/osv-scanner-action/osv-reporter-action@8018483926dd235b3013d8c88023e644b9f8e09e # v2.3.3
        with:
          scan-args: |-
            --output=${{ inputs.matrix-property }}${{ inputs.results-file-name }}
            --new=${{ inputs.matrix-property }}results.json
            --gh-annotations=false
            --fail-on-vuln=${{ inputs.fail-on-vuln }}
      - name: "Upload artifact"
        id: "upload_artifact"
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ inputs.matrix-property }}OSV Scanner SARIF file
          path: ${{ inputs.matrix-property }}${{ inputs.results-file-name }}
          retention-days: 5
      - name: "Upload to code-scanning"
        if: "${{ !cancelled() && inputs.upload-sarif == true }}"
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
        with:
          sarif_file: ${{ inputs.matrix-property }}${{ inputs.results-file-name }}
      - name: "Print Code Scanning URL"
        if: "${{ !cancelled() && inputs.upload-sarif == true }}"
        run: |
          echo "View the OSV-Scanner results in the 'Security' tab, using the following link:"
          echo "${{ github.server_url }}/${{ github.repository }}/security/code-scanning?query=is%3Aopen+branch%3A${GITHUB_REF_NAME}+tool%3Aosv-scanner"
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
      - name: "Error troubleshooter"
        if: ${{ always() && steps.upload_artifact.outcome == 'failure' }}
        run: |
          echo "::error::Artifact upload failed. This is most likely caused by a error during scanning earlier in the workflow."
          exit 1
