# SPDX-FileCopyrightText: {{ copyright_year }} {{ copyright_holder }}
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# v0.11.14
FROM ghcr.io/astral-sh/uv:0.11.14@sha256:1025398289b62de8269e70c45b91ffa37c373f38118d7da036fb8bb8efc85d97 AS uv

# 3.0.6-3.13
FROM mcr.microsoft.com/devcontainers/python:3.0.6-3.13@sha256:9b0762901a555c31c2c63824cb5b1ade77da939500e034317b8d09578b94ba0e

COPY --from=uv /uv /uvx /usr/local/bin/

# 1.50.0
RUN UV_TOOL_BIN_DIR=/usr/local/bin UV_TOOL_DIR=/opt/uv-tools uv tool install rust-just==1.50.0

USER vscode

HEALTHCHECK --interval=5m --timeout=5s --start-period=10s --retries=3 \
    CMD uv --version && just --version
