#!/usr/bin/env -S uv run --script
# SPDX-FileCopyrightText: 2026 Avish Jha <avish.j@pm.me>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# /// script
# requires-python = ">=3.13"
# dependencies = []
# ///
"""Make a meaningful change in the smoke-repo PR branch.

Run from cwd of smoke-repo PR branch; produces edits that trigger every
path-filtered workflow in the generated ci.yml. Path-filter coverage:

- python   -> src/<module>/__init__.py (trailing comment), tests/test_verify.py (new no-op)
- docker   -> Dockerfile (trailing comment)
- docs     -> README.md (trailing marker)

Filters intentionally NOT triggered:
- workflows  -> we don't mutate CI itself
- config     -> every entry there has side effects (lockfile, EOL, probot, sonar)
"""

from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path

STAMP = dt.datetime.now(dt.UTC).isoformat()
MARK = f"verify {STAMP}"


def append_line(path: Path, line: str) -> None:
    with path.open("a", encoding="utf-8") as f:
        f.write(line if line.endswith("\n") else line + "\n")


def add_noop_test() -> None:
    Path("tests/test_verify.py").write_text(
        f'"""Auto-generated by verify/trigger.py at {STAMP}."""\n\n'
        "import pytest\n\n\n"
        "@pytest.mark.unit\n"
        "def test_verify_noop() -> None:\n"
        "    assert True\n",
        encoding="utf-8",
    )


def find_module_init() -> Path:
    candidates = [p for p in Path("src").glob("*/__init__.py")]
    if len(candidates) != 1:
        raise SystemExit(f"trigger: expected 1 src/*/__init__.py, found {len(candidates)}")
    return candidates[0]


def main() -> int:
    append_line(find_module_init(), f"# {MARK}")
    add_noop_test()
    append_line(Path("Dockerfile"), f"# {MARK}")
    append_line(Path("README.md"), f"\n<!-- {MARK} -->")
    return 0


if __name__ == "__main__":
    sys.exit(main())
